### PR TITLE
Fix vaillant hcmode properties

### PR DESCRIPTION
**Pull request by 27ascii**
Fixed duplicate mapping of hcmode keys causing invalid hcmode values in ehp status.

### CODE REVIEW

**Comment by Kolbi** [comment]
*push to merge*

**Comment by 27ascii** [comment]
@Kolbi The branch is now in sync with the master.

**Comment by john30** [comment]
reworked+merged in cffa1cec

**Comment by john30** [comment]
please check the [next](https://ebus.github.io/next/) generated csvs with ebusd 24.1 (or current source) as described there or by using a local clone of https://github.com/eBUS/ebus.github.io and using the "next" folder in there

**Comment by 27ascii** [comment]
@john30 
Works for me. The old version reports 
```
ebusd/ehp/SetMode: {
     "hcmode": {"value": 3}
}
```

the `next` has the proper value:
```
ebusd/ehp/SetMode: {
     "hcmode": {"value": "water"}
}
```

**Pull request closed without merging**
