### PR TITLE
Updated special modes for VRC 700

### PR DESCRIPTION
**Pull request by stadid**
Some special operating modes are missing for VRC 700, added them. Successfully tested with VRC700/4. Not sure if English mode names fit for the German file. Please change to German if necessary.

### CODE REVIEW

**Comment by DanielTheCoder** [comment]
Hey @stadid, I don't know how to update the csv files but can contribute the German translation.

4=Ein Tag außer Haus
5=Ein Tag zu Hause
6=1x Speicherladung

Would be great if you can add it so that we can get it merged.

**Comment by stadid** [comment]
> Hey @stadid, I don't know how to update the csv files but can contribute the German translation.
> 
> 4=Ein Tag außer Haus 5=Ein Tag zu Hause 6=1x Speicherladung
> 
> Would be great if you can add it so that we can get it merged.

Done. Please note that I have to make it lowercase and remove spaces, following the format of the  other values.

**Comment by pepsonEL** [comment]
But in my VRC700/6 when i activate 1 load water it show sfmode as "load"

**Comment by stadid** [comment]
> But in my VRC700/6 when i activate 1 load water it show sfmode as "load"

Most probably you are using current config file for vrc 700 where mode 6 named as "load"
Once above changes are commited to the main branch (currently they are not) you can see the new mode names.

**Comment by pepsonEL** [comment]
But why it is propose to change it ?

**Comment by stadid** [comment]
> But why it is propose to change it ?

To better conform with the vrc 700 menu and manual, as "load" do not linked in any way with English manual and menu where this mode is called  "Cylinder boost". But for compatibility reasons it's better to leave mode 6 name as is. I'll make necessary corrections.

**Pull request merged**
