### PR TITLE
Symlink VRT350 for HW=7102

### PR DESCRIPTION
**Pull request by wlcrs**
As a replacement for PR #211 . 

```
2022-01-28 19:42:56.998 [bus notice] scan 15: ;Vaillant;35000;0114;7102
2022-01-28 19:42:56.998 [update notice] store 15 ident: done
2022-01-28 19:42:56.998 [update notice] sent scan-read scan.15  QQ=31: Vaillant;35000;0114;7102
2022-01-28 19:42:56.999 [bus notice] scan 15: ;Vaillant;35000;0114;7102
2022-01-28 19:42:57.180 [update notice] sent unknown MS cmd: 3115b5090124 / 09003231323034393030
2022-01-28 19:42:57.353 [update notice] sent scan-read scan.15 id QQ=31: 
2022-01-28 19:42:57.529 [update notice] sent scan-read scan.15 id QQ=31: 
2022-01-28 19:42:57.704 [update notice] sent scan-read scan.15 id QQ=31: 21;20;49;0020124473;0082;031767;N7
2022-01-28 19:42:57.704 [bus notice] scan 15: ;21;20;49;0020124473;0082;031767;N7
2022-01-28 19:42:57.711 [main notice] read scan config file vaillant/15.35000.HW7102.csv for ID "35000", SW0114, HW7102
2022-01-28 19:42:57.716 [main notice] found messages: 347 (2 conditional on 25 conditions, 0 poll, 10 update)
```

Some notes: 
- does not work if I use `15.350.HW7102.csv` , it needs the extra zeros in the name
- There was a mismatch in the documentation on https://github.com/john30/ebusd/wiki/4.7.-Automatic-configuration. I changed the format from `ZZ.[ID.][*.][SW????.][*.][HW????.][*.]csv` to `ZZ.[ID.][*.][HW????.][*.][SW????.][*.]csv` as that seemed to be working.

### CODE REVIEW

**Comment by TeunvandeBerg** [comment]
@wlcrs thanks!
Closed https://github.com/john30/ebusd-configuration/pull/211 . Added a reference to [this ](https://github.com/john30/ebusd-configuration/pull/211)PR.

**Review by john30 — CHANGES_REQUESTED** [review]
file names should be 15.350.HW7102.csv

**Comment by wlcrs** [comment]
Hi @john30 . As already mentioned in the first post: without the extra zeros this file is not picked up by ebusd for my installation. Has this been fixed in the meantime?

**Comment by john30** [comment]
> Hi @john30 . As already mentioned in the first post: without the extra zeros this file is not picked up by ebusd for my installation. Has this been fixed in the meantime?

I don't see an issue with that

**Review by john30 — APPROVED** [review]

**Comment by john30** [comment]
renamed as requested

**Pull request merged**
