### PR TITLE
Hc1SFMode and Hc2SFMode R/W for Calormatic 470f

### PR DESCRIPTION
**Pull request by guillaumezin**

### CODE REVIEW

**Comment by guillaumezin** [comment]
Hello, did you see that I added holiday mode for VRC470F in patch 20d4d5?

**Comment by john30** [comment]
yes, but it is not sure that it will work on all variants and all software versions of the 470.
which version do you have?

**Comment by guillaumezin** [comment]
Boiler 6.09
VR21 1.15
Base 1.20
VR61 4.18
Display 1.24

**Comment by guillaumezin** [comment]
"MF": {"value": "Vaillant"}, "ID": {"value": "F4700"}, "SW": {"value": "0114"}, "HW": {"value": "6102"}
 "MF": {"value": "Vaillant"}, "ID": {"value": "BAI00"}, "SW": {"value": "0609"}, "HW": {"value": "5502"}
  "MF": {"value": "Vaillant"}, "ID": {"value": "V6100"}, "SW": {"value": "0418"}, "HW": {"value": "1902"}

**Comment by john30** [comment]
ok, I don't think it will hurt anyone

**Comment by ghosty-be** [comment]
oh I found something in the logs that looks like this info:
2018-04-11 12:10:40.348 [main notice] read scan config file /etc/ebusd/vaillant/08.bai.csv for ID "bai00", SW0604, HW5502
2018-04-11 12:10:44.959 [main notice] read scan config file /etc/ebusd/vaillant/15.470.csv for ID "47000", SW0420, HW1403

**Pull request merged**
