### PR TITLE
better support for ecoVIT exclusiv VKK 0010007510

### PR DESCRIPTION
**Pull request by jabdoa2**
Fix `FlowSetPotmeter` and `PrEnergy*` for ecoVIT exclusiv VKK 0010007510. This is mostly a copy of 0010007508 with changes for the two entries:
- Use correct address for `FlowSetPotmeter`
- Allow writes (`wi`) for all `PrEnergy*` settings. Otherwise, they will overflow and you cannot reset them
- Use correct address `PrEnergy*`. Those might as well be broken in "0010007508" as `PrEnergySumHwc2` is missing and `PrEnergySumHwc1` kind of duplicate.

Resolves some of the issues from #409

### CODE REVIEW

**Comment by john30** [comment]
reworked+merged in 21e5bbea921005f27a6ba261f348a828aff3a8fa

**Comment by jabdoa2** [comment]
@john30 did you somehow adjust the addresses for `PrEnergy`? I did not manage to identify that part in your commit. Maybe you solved it another way?

**Comment by john30** [comment]
please check the [next](https://ebus.github.io/next/) generated csvs with ebusd 24.1 (or current source) as described there or by using a local clone of https://github.com/eBUS/ebus.github.io and using the "next" folder in there

**Comment by jabdoa2** [comment]
> please check the [next](https://ebus.github.io/next/) generated csvs with ebusd 24.1 (or current source) as described there or by using a local clone of https://github.com/eBUS/ebus.github.io and using the "next" folder in there

Looks right. Thanks!

**Comment by sr258** [comment]
Following up on this — the fix here is present in `master`'s TypeSpec source for `bai.0010015600.inc`:

```
@inherit(r, wi_1)
@ext(0xf5, 0)
model PrEnergySumHc1 { ... }
```

and in `master`'s frozen `archived/en/vaillant/bai.0010015600.inc` / `archived/de/vaillant/bai.0010015600.inc` mirrors (both show `r;wi`).

However, the live production CDN at `https://ebus.github.io/{en,de}/vaillant/bai.0010015600.inc` (what ebusd's default `--configpath` actually resolves to) still serves the pre-fix content, with the write gated behind `install_NOT_YET_CONFIRMED` — a level no `--accesslevel` setting can satisfy:

```
w,,install_NOT_YET_CONFIRMED,PrEnergySumHc1,PrEnergySumCH1,,,b509,0ef500,value,,ULG,,,Maintenance data
```

I also checked `https://ebus.github.io/next/en/vaillant/bai.0010015600.inc` (the path referenced above for verification) — same stale result there.

The `ebus.github.io` repo's submodule pin of `ebusd-configuration` is `a6c2904f` (2026-04-19), which postdates the fix commit (`21e5bbe`, Dec 2024), so the source should be included — but the published legacy CSV for this specific product ID doesn't reflect it. Last "import changes" sync affecting this file was 2026-02-01.

Impact: users of this hardware (`ID=BAI00;SW=0405;HW=9602`, product ID `0010021926` → resolves via `[id_hw=9602]` to `bai.0010015600.inc`) still can't reset the `PrEnergySumHc1` maintenance counter via ebusd/MQTT even though the fix has been merged for over a year, because the live CDN ebusd actually fetches from hasn't picked it up.

I also tried pointing `--configpath` directly at `https://raw.githubusercontent.com/john30/ebusd-configuration/master/archived` (and a jsdelivr mirror of the same) as a workaround, but that only has the raw `.inc` files without the generated index/mapping that `--scanconfig` needs, so it fails to resolve anything.

Could the CDN generation/publish step be re-run, or is there a separate confirmation gate blocking this specific product ID's `PrEnergy*` fields from being promoted to the published feed? `ebus.github.io` itself has issues disabled, so posting here instead.

**Pull request closed without merging**
