### PR TITLE
Update bai.308523.inc

### PR DESCRIPTION
**Pull request by HiQual**
Add setmodeoverride per issue #361

### CODE REVIEW

**Comment by john30** [comment]
reworked and merged in ba4c7491

**Comment by john30** [comment]
please check the [next](https://ebus.github.io/next/) generated csvs with ebusd 24.1 (or current source) as described there or by using a local clone of https://github.com/eBUS/ebus.github.io and using the "next" folder in there

**Comment by HiQual** [comment]
Working ...
image
Many thanks John - much appreciated.

**Comment by rasika-jay** [comment]
hey @john30, sorry to bring up an old discussion - curious to know if `SetModeOverride` still works on the latest config files? I believe this was to help modulation not working correctly?

cc: @HiQual

**Comment by rasika-jay** [comment]
> @rasika-jay Please see ... #537

Thanks @HiQual, I've updated my config and the command itself is working, but have to wait to see if modulation is working.

Do you know the origins of `setmode1` / `setmode2` or what they do? Just trying to understand why the default `SetMode` doesn't use it/difference.

**Pull request closed without merging**
