### PR TITLE
added ventilation

### PR DESCRIPTION
**Pull request by antasun**
with this config you can choose the stages of the ventilation system (possible values: 1, 2, 3, 4 ,5, 6)

### CODE REVIEW

**Comment by straccio** [comment]
I give it a try....

**Comment by straccio** [comment]
I can confirm this PR, it's work!
Can be awesome have Current Room Humidity from the vrc700...

**Comment by antasun** [comment]
should also be possible ... if I have time, I try to add that

**Comment by straccio** [comment]
Tnx,
How? Can you teach me? or give me some documentation?

**Comment by john30** [comment]
done with #191

**Pull request closed without merging**
