### PR TITLE
Initial commit for Protherm Panther Condens 30 KKO + Thermolink P/2

### PR DESCRIPTION
**Pull request by cogano**

### CODE REVIEW

**Comment by john30** [comment]
Could you run a scan and provide the scan result please?

**Comment by cogano** [comment]
scan full && scan result:

    08;Vaillant;BAI00;0502;3302;21144000;100088631;610005132;N4
    14;Vaillant;BADID;0000;0002;E7f_2  �;211440002;011808400;82
    15;Vaillant;E7f_2;0001;8002;21144000;201180840;082005051;N8
    16;Vaillant;E7f_2;0203;7502;21144000;201180840;082005051;N8
    26;Vaillant;E7f_2;0001;8002;21144000;201180840;082005051;N8
    35;Vaillant;E7f_2;0001;8002;11440002;011808400;82005051N;8�

Protherm was acquired by Vaillant some time ago. While some of the internals are similar (BAI00), the actual commands from bai00.csv do not really work - in Protherm, some functionality is missing, some commands differ.
The csv is definitely a work-in-progress, at the moment it includes what I could sniff and a few more 'read' commands for info I was interested in.

**Comment by john30** [comment]
Could you run the following command after initiating a scan and paste the result please:
> echo "scan result"|nc localhost 8888|egrep "^14"|hexdump -C

**Comment by cogano** [comment]
$ echo "scan result" | nc localhost 8888 | egrep "^14" | hexdump -C
    00000000  31 34 3b 56 61 69 6c 6c  61 6e 74 3b 42 41 44 49  |14;Vaillant;BADI|
    00000010  44 3b 30 30 30 30 3b 30  30 30 32 0a              |D;0000;0002.|
    0000001c

sorry for the delay.

**Comment by john30** [comment]
no problem.
Thanks for the post, but this time the tail seems to be missing (the interesting part would have been the one starting with "E7f_2" in hex).

**Comment by cogano** [comment]
Ah, it required to wait until "scan full" completes. I was connected on some dummy terminal and had to use egrep -a, I hope it does not alter the actual output from ebusd:

    $ echo "scan result" | nc localhost 8888 | egrep -a "BADI" | hexdump -C
    00000000  31 34 3b 56 61 69 6c 6c  61 6e 74 3b 42 41 44 49  |14;Vaillant;BADI|
    00000010  44 3b 30 30 30 31 3b 38  30 30 32 3b 45 37 66 5f  |D;0001;8002;E7f_|
    00000020  32 20 20 80 3b 32 30 31  31 38 30 38 34 30 3b 32  |2  .;201180840;2|
    00000030  31 31 34 34 30 30 30 32  3b 30 31 0a              |11440002;01.|
    0000003c

**Comment by cogano** [comment]
@John30: did the info help?

**Comment by john30** [comment]
no, the ID is not part of the MDB and thus I cannot determine the full set of valid configuration messages

**Pull request merged**
