### PR TITLE
Support 0010021888 Vaillant ecoTEC plus 256/5-5

### PR DESCRIPTION
**Pull request by cameleon77**
Better match for 0010021888 Vaillant ecoTEC plus 256/5-5

### CODE REVIEW

**Comment by andig** [comment]
Looks like https://github.com/john30/ebusd-configuration/pull/107. This seems to be a good default for newer ecoTec models.

**Comment by cameleon77** [comment]
Exactly, I've done it based on your findings :+1:

**Comment by john30** [comment]
do all these devices share the same HW and SW version?
maybe it would be better to use that as the default selection criteria...

**Comment by cameleon77** [comment]
in my case it is SW=0104 HW=7803
0010021888 Vaillant ecoTEC plus 256/5-5

**Comment by john30** [comment]
hm okay thats totally different from what is described in #106, so lets stick to the selection by product ID

**Pull request merged**
